# Generated by Django 4.2.18 on 2025-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_media', models.CharField(choices=[('?', '?'), ('ok', 'In stock'), ('no', 'Out of stock')], default='?', max_length=2)),
            ],
        ),
    ]
